name: Trigger Webhook

on:
  push:
    branches: [main]

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Webhook
        uses: peter-evans/webhook@v1.4.0
        with:
          url: https://0545-2401-4900-1c39-5b84-8de8-f0df-13b-3bb2.in.ngrok.io/job/Xray-demo/build # Replace this with the URL of your webhook
          method: POST
          body: '{"job": "Xray-demo"}' # Replace this with the name of your Jenkins job
