name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  trigger_jenkins_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub webhook
        uses: marvinpinto/action-github-webhook@v1.4.0
        with:
          webhook_url: 'https://b319-2401-4900-1c39-5b84-9227-f687-fda8-fd9f.in.ngrok.io/github-webhook/'
          content_type: 'application/json'
          method: 'POST'
          body: '{"event_type": "run-jenkins-job"}'
          secret: ${{ secrets.WEBHOOK_SECRET }}

      - name: Check webhook response
        run: |
          echo ${{ steps.trigger_github_webhook.outputs.status_code }}
          echo ${{ steps.trigger_github_webhook.outputs.response }}
          
  jenkins_job:
    needs: trigger_jenkins_job
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins job
        uses: appleboy/jenkins-action@master
        with:
          url: 'https://b319-2401-4900-1c39-5b84-9227-f687-fda8-fd9f.in.ngrok.io/github-webhook/'
          user: 'anshuman0888'
          token: '${{ secrets.JENKINS_TOKEN }}'
          job: 'xray-linear'
