name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  trigger_jenkins_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub webhook
        uses: distributhor/webhook-action@master
        with:
          url: 'https://api.github.com/repos/postman-newman/webhooks/dispatches'
          method: 'POST'
          headers: '{"Content-Type":"application/json", "Authorization": "Bearer ${{ secrets.REPO_ACCESS_TOKEN }}"}'
          body: '{"event_type": "run-jenkins-job"}'
          
      - name: Check webhook response
        run: |
          echo ${{ steps.trigger_github_webhook.outputs.status_code }}
          echo ${{ steps.trigger_github_webhook.outputs.response }}
